/*------------------------------------------------ Save ----------------------------------------------*/
// Save game variables
save = {
	saveGame: function(){
		// Player
		$.jStorage.set("playerLevel", player.level);
		$.jStorage.set("playerExp", player.exp);
		$.jStorage.set("playerUpgradePoints", player.upgradePoints);
		$.jStorage.set("playerHandicap", player.handicap);
		// Upgrades
		$.jStorage.set("upgradesShieldDuration", upgrades.shieldDuration);
		$.jStorage.set("upgradesShieldCooldown",upgrades.shieldCooldown);
		$.jStorage.set("upgradesItemDropRate",upgrades.itemDropRate);
		$.jStorage.set("upgradesHealthRegeneration",upgrades.healthRegeneration);
		$.jStorage.set("upgradesWeaponDamageMultiplier",upgrades.weaponDamageMultiplier);
		// Options
		if(menus.particlesOn){
			$.jStorage.set("menusParticlesOn",0);
		}
		else{
			$.jStorage.set("menusParticlesOn",1);
		}
		if(menus.autoShootOn){
			$.jStorage.set("menusAutoShootOn",0);
		}
		else{
			$.jStorage.set("menusAutoShootOn",1);
		}
		if(menus.soundOn){
			$.jStorage.set("menusSoundOn",0);
		}
		else{
			$.jStorage.set("menusSoundOn",1);
		}
		if(menus.textAnimationsOn){
			$.jStorage.set("menusTextAnimationsOn",0);
		}
		else{
			$.jStorage.set("menusTextAnimationsOn",1);
		}
		// Hyper Mode
		if(hyper.unlocked){
			$.jStorage.set("hyperUnlocked",1);
		}
		else{
			$.jStorage.set("hyperUnlocked",0);
		}
		$.jStorage.set("hyperEasyHighScore",hyper.easyHighScore);
		$.jStorage.set("hyperNormalHighScore",hyper.normalHighScore);
		$.jStorage.set("hyperHardHighScore",hyper.hardHighScore);
		$.jStorage.set("hyperInsaneHighScore",hyper.insaneHighScore);
		// Scores
		$.jStorage.set("levelsLevelScoreArray0",levels.levelScoreArray[0]);
		$.jStorage.set("levelsLevelScoreArray1",levels.levelScoreArray[1]);
		$.jStorage.set("levelsLevelScoreArray2",levels.levelScoreArray[2]);
		$.jStorage.set("levelsLevelScoreArray3",levels.levelScoreArray[3]);
		$.jStorage.set("levelsLevelScoreArray4",levels.levelScoreArray[4]);
		$.jStorage.set("levelsLevelScoreArray5",levels.levelScoreArray[5]);
		$.jStorage.set("levelsLevelScoreArray6",levels.levelScoreArray[6]);
		$.jStorage.set("levelsLevelScoreArray7",levels.levelScoreArray[7]);
		$.jStorage.set("levelsLevelScoreArray8",levels.levelScoreArray[8]);
		$.jStorage.set("levelsLevelScoreArray9",levels.levelScoreArray[9]);
		$.jStorage.set("levelsLevelScoreArray10",levels.levelScoreArray[10]);
		$.jStorage.set("levelsLevelScoreArray11",levels.levelScoreArray[11]);
		$.jStorage.set("levelsLevelScoreArray12",levels.levelScoreArray[12]);
		$.jStorage.set("levelsLevelScoreArray13",levels.levelScoreArray[13]);
		$.jStorage.set("levelsLevelScoreArray14",levels.levelScoreArray[14]);
		$.jStorage.set("levelsLevelScoreArray15",levels.levelScoreArray[15]);
		$.jStorage.set("levelsLevelScoreArray16",levels.levelScoreArray[16]);
		$.jStorage.set("levelsLevelScoreArray17",levels.levelScoreArray[17]);
		$.jStorage.set("levelsLevelScoreArray18",levels.levelScoreArray[18]);
		$.jStorage.set("levelsLevelScoreArray19",levels.levelScoreArray[19]);
		$.jStorage.set("levelsLevelScoreArray20",levels.levelScoreArray[20]);
		$.jStorage.set("levelsLevelScoreArray21",levels.levelScoreArray[21]);
		$.jStorage.set("levelsLevelScoreArray22",levels.levelScoreArray[22]);
		$.jStorage.set("levelsLevelScoreArray23",levels.levelScoreArray[23]);
		$.jStorage.set("levelsLevelScoreArray24",levels.levelScoreArray[24]);
		$.jStorage.set("levelsLevelScoreArray25",levels.levelScoreArray[25]);
		$.jStorage.set("levelsLevelScoreArray26",levels.levelScoreArray[26]);
		$.jStorage.set("levelsLevelScoreArray27",levels.levelScoreArray[27]);
		$.jStorage.set("levelsLevelScoreArray28",levels.levelScoreArray[28]);
		$.jStorage.set("levelsLevelScoreArray29",levels.levelScoreArray[29]);
		$.jStorage.set("levelsLevelScoreArray30",levels.levelScoreArray[30]);
		$.jStorage.set("levelsLevelScoreArray31",levels.levelScoreArray[31]);
		$.jStorage.set("levelsLevelScoreArray32",levels.levelScoreArray[32]);
		$.jStorage.set("levelsLevelScoreArray33",levels.levelScoreArray[33]);
		$.jStorage.set("levelsLevelScoreArray34",levels.levelScoreArray[34]);
		$.jStorage.set("levelsLevelScoreArray35",levels.levelScoreArray[35]);
		$.jStorage.set("levelsLevelScoreArray36",levels.levelScoreArray[36]);
		// Zones
		if(levels.zone2Unlocked){
			$.jStorage.set("levelsZone2Unlocked",1);
		}
		else{
			$.jStorage.set("levelsZone2Unlocked",0);
		}
		if(levels.zone3Unlocked){
			$.jStorage.set("levelsZone3Unlocked",1);
		}
		else{
			$.jStorage.set("levelsZone3Unlocked",0);
		}
		if(levels.zone4Unlocked){
			$.jStorage.set("levelsZone4Unlocked",1);
		}
		else{
			$.jStorage.set("levelsZone4Unlocked",0);
		}
		if(levels.zone5Unlocked){
			$.jStorage.set("levelsZone5Unlocked",1);
		}
		else{
			$.jStorage.set("levelsZone5Unlocked",0);
		}
		if(levels.zone6Unlocked){
			$.jStorage.set("levelsZone6Unlocked",1);
		}
		else{
			$.jStorage.set("levelsZone6Unlocked",0);
		}
		// Levels
		if(levels.levelUnlockArray[0]){
			$.jStorage.set("levelsLevel0Unlocked",1);
		}
		else{
			$.jStorage.set("levelsLevel0Unlocked",0);
		}
		// Level 1 is always unlocked
		if(levels.levelUnlockArray[1]){
			$.jStorage.set("levelsLevel1Unlocked",1);
		}
		else{
			$.jStorage.set("levelsLevel1Unlocked",1);
		}
		if(levels.levelUnlockArray[2]){
			$.jStorage.set("levelsLevel2Unlocked",1);
		}
		else{
			$.jStorage.set("levelsLevel2Unlocked",0);
		}
		if(levels.levelUnlockArray[3]){
			$.jStorage.set("levelsLevel3Unlocked",1);
		}
		else{
			$.jStorage.set("levelsLevel3Unlocked",0);
		}
		if(levels.levelUnlockArray[4]){
			$.jStorage.set("levelsLevel4Unlocked",1);
		}
		else{
			$.jStorage.set("levelsLevel4Unlocked",0);
		}
		if(levels.levelUnlockArray[5]){
			$.jStorage.set("levelsLevel5Unlocked",1);
		}
		else{
			$.jStorage.set("levelsLevel5Unlocked",0);
		}
		if(levels.levelUnlockArray[6]){
			$.jStorage.set("levelsLevel6Unlocked",1);
		}
		else{
			$.jStorage.set("levelsLevel6Unlocked",0);
		}
		if(levels.levelUnlockArray[7]){
			$.jStorage.set("levelsLevel7Unlocked",1);
		}
		else{
			$.jStorage.set("levelsLevel7Unlocked",0);
		}
		if(levels.levelUnlockArray[8]){
			$.jStorage.set("levelsLevel8Unlocked",1);
		}
		else{
			$.jStorage.set("levelsLevel8Unlocked",0);
		}
		if(levels.levelUnlockArray[9]){
			$.jStorage.set("levelsLevel9Unlocked",1);
		}
		else{
			$.jStorage.set("levelsLevel9Unlocked",0);
		}
		if(levels.levelUnlockArray[10]){
			$.jStorage.set("levelsLevel10Unlocked",1);
		}
		else{
			$.jStorage.set("levelsLevel10Unlocked",0);
		}
		if(levels.levelUnlockArray[11]){
			$.jStorage.set("levelsLevel11Unlocked",1);
		}
		else{
			$.jStorage.set("levelsLevel11Unlocked",0);
		}
		if(levels.levelUnlockArray[12]){
			$.jStorage.set("levelsLevel12Unlocked",1);
		}
		else{
			$.jStorage.set("levelsLevel12Unlocked",0);
		}
		if(levels.levelUnlockArray[13]){
			$.jStorage.set("levelsLevel13Unlocked",1);
		}
		else{
			$.jStorage.set("levelsLevel13Unlocked",0);
		}
		if(levels.levelUnlockArray[14]){
			$.jStorage.set("levelsLevel14Unlocked",1);
		}
		else{
			$.jStorage.set("levelsLevel14Unlocked",0);
		}
		if(levels.levelUnlockArray[15]){
			$.jStorage.set("levelsLevel15Unlocked",1);
		}
		else{
			$.jStorage.set("levelsLevel15Unlocked",0);
		}
		if(levels.levelUnlockArray[16]){
			$.jStorage.set("levelsLevel16Unlocked",1);
		}
		else{
			$.jStorage.set("levelsLevel16Unlocked",0);
		}
		if(levels.levelUnlockArray[17]){
			$.jStorage.set("levelsLevel17Unlocked",1);
		}
		else{
			$.jStorage.set("levelsLevel17Unlocked",0);
		}
		if(levels.levelUnlockArray[18]){
			$.jStorage.set("levelsLevel18Unlocked",1);
		}
		else{
			$.jStorage.set("levelsLevel18Unlocked",0);
		}
		if(levels.levelUnlockArray[19]){
			$.jStorage.set("levelsLevel19Unlocked",1);
		}
		else{
			$.jStorage.set("levelsLevel19Unlocked",0);
		}
		if(levels.levelUnlockArray[20]){
			$.jStorage.set("levelsLevel20Unlocked",1);
		}
		else{
			$.jStorage.set("levelsLevel20Unlocked",0);
		}
		if(levels.levelUnlockArray[21]){
			$.jStorage.set("levelsLevel21Unlocked",1);
		}
		else{
			$.jStorage.set("levelsLevel21Unlocked",0);
		}
		if(levels.levelUnlockArray[22]){
			$.jStorage.set("levelsLevel22Unlocked",1);
		}
		else{
			$.jStorage.set("levelsLevel22Unlocked",0);
		}
		if(levels.levelUnlockArray[23]){
			$.jStorage.set("levelsLevel23Unlocked",1);
		}
		else{
			$.jStorage.set("levelsLevel23Unlocked",0);
		}
		if(levels.levelUnlockArray[24]){
			$.jStorage.set("levelsLevel24Unlocked",1);
		}
		else{
			$.jStorage.set("levelsLevel24Unlocked",0);
		}
		if(levels.levelUnlockArray[25]){
			$.jStorage.set("levelsLevel25Unlocked",1);
		}
		else{
			$.jStorage.set("levelsLevel25Unlocked",0);
		}
		if(levels.levelUnlockArray[26]){
			$.jStorage.set("levelsLevel26Unlocked",1);
		}
		else{
			$.jStorage.set("levelsLevel26Unlocked",0);
		}
		if(levels.levelUnlockArray[27]){
			$.jStorage.set("levelsLevel27Unlocked",1);
		}
		else{
			$.jStorage.set("levelsLevel27Unlocked",0);
		}
		if(levels.levelUnlockArray[28]){
			$.jStorage.set("levelsLevel28Unlocked",1);
		}
		else{
			$.jStorage.set("levelsLevel28Unlocked",0);
		}
		if(levels.levelUnlockArray[29]){
			$.jStorage.set("levelsLevel29Unlocked",1);
		}
		else{
			$.jStorage.set("levelsLevel29Unlocked",0);
		}
		if(levels.levelUnlockArray[30]){
			$.jStorage.set("levelsLevel30Unlocked",1);
		}
		else{
			$.jStorage.set("levelsLevel30Unlocked",0);
		}
		if(levels.levelUnlockArray[31]){
			$.jStorage.set("levelsLevel31Unlocked",1);
		}
		else{
			$.jStorage.set("levelsLevel31Unlocked",0);
		}
		if(levels.levelUnlockArray[32]){
			$.jStorage.set("levelsLevel32Unlocked",1);
		}
		else{
			$.jStorage.set("levelsLevel32Unlocked",0);
		}
		if(levels.levelUnlockArray[33]){
			$.jStorage.set("levelsLevel33Unlocked",1);
		}
		else{
			$.jStorage.set("levelsLevel33Unlocked",0);
		}
		if(levels.levelUnlockArray[34]){
			$.jStorage.set("levelsLevel34Unlocked",1);
		}
		else{
			$.jStorage.set("levelsLevel34Unlocked",0);
		}
		if(levels.levelUnlockArray[35]){
			$.jStorage.set("levelsLevel35Unlocked",1);
		}
		else{
			$.jStorage.set("levelsLevel35Unlocked",0);
		}
		if(levels.levelUnlockArray[36]){
			$.jStorage.set("levelsLevel36Unlocked",1);
		}
		else{
			$.jStorage.set("levelsLevel36Unlocked",0);
		}
	}
};